version: '3.7'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - node
    networks:
      - default-network

  node:
    container_name: node
    build:
      context: ./node
    entrypoint: [ "dockerize", "-wait", "tcp://db:3306", "-timeout", "20s", "npm", "start" ]
    volumes:
      - ./node:/app
    depends_on:
      - db
    networks:
      - default-network

  db:
    build:
      context: ./mysql
    container_name: db
    restart: always
    tty: true
    networks:
      - default-network
    volumes:
      - ./mysql/volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

networks:
  default-network:
    driver: bridge